name: Runner Test

on:
  push:

jobs:
  runner-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thread: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17 (# ${{ matrix.thread }})
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build (# ${{ matrix.thread }})
        run: mvn -B clean package

      - name: Run (# ${{ matrix.thread }})
        run:  java -classpath "target/classes:target/lib/httpclient5-5.2.1.jar:target/lib/httpcore5-5.2.jar:target/lib/httpcore5-h2-5.2.jar:target/lib/slf4j-api-1.7.36.jar" org.example.Main

